export const USER_SIGNIN_REQUEST='USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS='USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL='USER_SIGNIN_FAIL';
export const USER_SIGNOUT='USER_SIGNOUT';

export const UPDATE_REQUEST='UPDATE_REQUEST';
export const UPDATE_SUCCESS='UPDATE_SUCCESS';
export const UPDATE_FAIL='UPDATE_FAIL';


export const GET_OTP_REQUEST='GET_OTP_REQUEST';
export const GET_OTP_SUCCESS='GET_OTP_SUCCESS'
export const GET_OTP_FAIL='GET_OTP_FAIL';

export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL';
